version: 2.1

jobs:

  build-and-test:

    machine:

      image: ubuntu-2204:2024.01.2

    steps:

      - checkout

      - run: make deps

      - run: make lint

      - run: make test

      - run: make docker_build

      - run: make docker_push

workflows:

  basic:

    jobs:
      - build-and-test

machines:
  docker_layer_caching: true 